### ISSUE TITLE
Add a library for http request

### ISSUE THREAD

**Issue by gianluca-sabena** [unicredit/react-boilerplate#1]
Include a library to make api calls to a remote api server. A possible candidate is https://github.com/github/fetch

**Comment by mfirry** [comment]
We already provide it Check out https://github.com/unicredit/react-boilerplate/blob/master/package.json#L47

**Comment by andreaferretti** [comment]
I think there are some issues with whatwg-fetch. The problem is that what-wg fetch is a polyfill, and it is not meant to be used as a common-js module via browserify (or an es6-module, which after compilation is the same thing). Even if it was, it would still need es6 promises, which have to be polyfilled as well.

So, I see two cases:

* either the browser natievely supports fetch and promises, in which cases whatwg-fetch will not be needed
* or it doesn't, in which case we would still not be able to use whatwg-fetch because of the lack of promises (and whatwg-fetch would have to be included on the page as a global polyfill in any case)

The case where the browser supports promises but no fetch seems to be empty, according to a cursory view at caniuse.

I suggest that we use [fetchify](https://www.npmjs.com/package/fetchify), that does the same but

* can be used as a browserify module, and
* works with any promise library, such as Bluebird or Q

See [here](https://github.com/andreaferretti/paths-js-react-demo/blob/master/js/github.jsx) for an example of usage.

**Comment by mfirry** [comment]
I see some possible options:
* import polyfills (namely [es6-promise](https://github.com/jakearchibald/es6-promise) and [fetch](whatwg-fetch)) as global imports inside `index.html`;
* forget about polyfills and just assume we're targeting browser that **do** support [fetch](http://caniuse.com/#feat=fetch) and [es6-promise](http://caniuse.com/#feat=promises);
* remove **http clients** altogether from this boilerplate and have *cloners* handle this issue according to their specific needs;
* use [fetchify](https://github.com/philmander/fetchify) or something similar

PR are accepted.

**Comment by gianluca-sabena** [comment]
In my opinion a spa needs to talk to a remote api server so I vote to include fetchify

**Comment by mfirry** [comment]
A _spa_ will eventually need many things. 
One of this things is connecting to some external API. 

This boilerplate is meant as a starting point tool-set for quickly developing UI components and layout using [React](https://facebook.github.io/react) and co. 
Connection with external API (either REST or GraphQL or any other format) is slightly out of the scope of this project.

I would rather leave it out rather than forcing any specific library at this point.
